### ISSUE TITLE
Import of lxml from local directory fails

### ISSUE THREAD

**Issue by CtrlShiftGo** [CtrlShiftGo/podcast-parakeet#3]
```
  File "podcastAnalyzer.py", line 7, in <module>
    import lxml.etree
ImportError: dlopen(/Users/Josh/Google Drive/Academics/Projects/podcast-parakeet/lxml/etree.so, 2): no suitable image found.  Did find:
	/Users/Josh/Google Drive/Academics/Projects/podcast-parakeet/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Current work around is removing the `lxml` directory temporarily.

**Comment by jleung51** [comment]
I'm willing to look into this issue. 

For clarification, removing the `lxml` directory is a successful workaround for Josh because he already has it installed as a dependency.

**Comment by CtrlShiftGo** [comment]
Thank you. I'll look into using the xml module instead as I believe that is part of the standard library.

**Comment by jleung51** [comment]
From my analysis, since the `lxml` module was compiled on my laptop, it is only compatible for my architecture. The compiled files won't function properly on your OSX or on most other computers. For example, on my other laptop, the error I'm receiving is:

```
Traceback (most recent call last):
  File "./podcastAnalyzer.py", line 7, in <module>
    from lxml import etree
ImportError: /home/jleung/Downloads/podcast-parakeet/lxml/etree.so: wrong ELF class: ELFCLASS64
```

Therefore, it seems like this prepackaging of the executables is not a good solution.

Some alternate options might be creating a `setup.py` or using a Docker image. @CtrlShiftGo, thoughts?

**Comment by CtrlShiftGo** [comment]
Thanks for investigating this issue.

A `setup.py` seems like the best solution for the time being as there are not many libraries that are required for this tool to function.

**Comment by CtrlShiftGo** [comment]
Since we're no longer distributing portions of the `lxml` library with the script this issue has been resolved.
